// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHotels.WebApi.Data;

namespace MyHotels.WebApi.Migrations
{
    [DbContext(typeof(MyHotelsDbContext))]
    partial class MyHotelsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyHotels.WebApi.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 3,
                            Code = "US",
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("MyHotels.WebApi.Domain.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Wrocław",
                            CountryId = 1,
                            Name = "Hotel Piast",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Warszawa",
                            CountryId = 1,
                            Name = "Center Warsaw",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Berlin",
                            CountryId = 2,
                            Name = "Waldorf Astoria",
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("MyHotels.WebApi.Domain.Hotel", b =>
                {
                    b.HasOne("MyHotels.WebApi.Domain.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MyHotels.WebApi.Domain.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
